### ISSUE TITLE
Tailwind CSS Support

### ISSUE THREAD

**Issue by KrishEnacton** [guocaoyi/create-chrome-ext#25]
Hi,
I want to apply tailwind css in this temporary can you describe How can I use it?

**Comment by dhatGuy** [comment]
[UnoCSS](https://unocss.dev/) works

**Comment by guocaoyi** [comment]
This is a simple entry-level scaffolding that doesn't take into account highly integrated technology stack options

**Comment by swapnawebdev** [comment]
![image](https://github.com/guocaoyi/create-chrome-ext/assets/148637423/09e641bb-fc73-4a22-bd6a-d16a88b7fd62)

getting this when i use UNOCSS
