### ISSUE TITLE
Add `jsconfig.json` in the template

### ISSUE THREAD

**Issue by rational-kunal** [guocaoyi/create-chrome-ext#36]
I've created some Chrome extensions using this tool and I always include a `jsconfig.json` file to enable automatic completion of the Chrome APIs. I suggest including a `jsconfig.json` in the basic templates.

Here's a sample of a `jsconfig.json` file:
```json
{"typeAcquisition": {"include": ["chrome"]}}
```

References:
- https://stackoverflow.com/a/73080274/8010366
- https://github.com/rational-kunal/List-to-Checklist/blob/main/jsconfig.json

**Comment by guocaoyi** [comment]
you can pull requests
