### ISSUE TITLE
Support for side panel

### ISSUE THREAD

**Issue by noe** [guocaoyi/create-chrome-ext#45]
Chrome supports a [side panel feature](https://developer.chrome.com/blog/extension-side-panel-launch/). Will it be supported by create-chrome-ext?

P.S.: thanks for the great project!

**Comment by lenaggar** [comment]
Wow, that's a nice coincidence, I was just going to opena new issue for sidePanel support for a new project I just started working on 😄

And yes, great project 🙌🏻

**Comment by guocaoyi** [comment]
@noe 
chrome.sidePanel
Permissions: sidePanel
Availability: Chrome 114+ MV3+
will supported at version `0.8.7`
Thanks for you advice

**Comment by guocaoyi** [comment]
this week

**Comment by jasan-s** [comment]
Is this releasing this week?

**Comment by guocaoyi** [comment]
@jasan-s @lenaggar @noe 
#47
