### ISSUE TITLE
vue-ts: error when starting dev server (v0.8.10)

### ISSUE THREAD

**Issue by spavel-gh** [guocaoyi/create-chrome-ext#51]
Release: [v0.8.10](https://github.com/guocaoyi/create-chrome-ext/releases/tag/v0.8.10)
Framework: » vue
Language: » vue-ts

How to Reproduce:
```
$ yarn install
$ yarn dev
```

Error:
```
failed to load config from C:\gits\test_ext\vue-ts\vite.config.ts
error when starting dev server:
file:///C:/gits/test_ext/vue-ts/node_modules/@vitejs/plugin-vue/dist/index.mjs:2
import { isCSSRequest, normalizePath as normalizePath$1, transformWithEsbuild, formatPostcssSourceMap, createFilter } from 'vite';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

As I noticed, the issue appeared after pull request #50 when the '@vitejs/plugin-vue' package was updated

> [template-vue-ts/package.json](https://github.com/guocaoyi/create-chrome-ext/pull/50/files#diff-226f2590d9b4e5717134aee8d0aa266f1e32c9d59c5928a32f1336d7204dc444R29)
> ```diff 
> - "@vitejs/plugin-vue": "^2.3.3",
> + "@vitejs/plugin-vue": "^4.4.0",
> ```

**Comment by guocaoyi** [comment]
Release: v0.8.11
Framework: » vue
Language: » vue-ts | vue-js

```json
"vite": "^4.4.11",
"@vitejs/plugin-vue": "^4.4.0",
"vue-tsc": "^1.8.18"
```
