### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by bot101** [guocaoyi/create-chrome-ext#59]
I can't seem to find a link to documentation for this library anywhere. This is my very first time checking out this library but cannot seem to find more information than what is currently in the Readme. Any pointers to proper documentation. I wouuld really liike to experiment with this as I have both new and existing extensions I am looking to build/migrate with a tool like this.

**Comment by guocaoyi** [comment]
@bot101 This is not a middleware or library; It's a scaffolding for building an initial, simple, out-of-box chrome extension template project
