### ISSUE TITLE
Creating a `react-ts` project results in a 404 page on initial bootstrap

### ISSUE THREAD

**Issue by ajhenry** [guocaoyi/create-chrome-ext#62]
Hi there, great work you're doing here!

I'm trying to use the `react-ts` starter for this project and am running into an issue with trying to get vite to load the default React page. 

The problem, after bootstrapping the project I am met with the following Browser error

![Image](https://github.com/guocaoyi/create-chrome-ext/assets/24923406/4f680c36-2797-40af-958d-0386a29f0e1e)

Reproduction

```sh
npm create chrome-ext@latest chrome -- --template react-ts
cd chrome
npm i
npm run dev
```

Vite compiles successfully but only serves the 404 page

**Comment by ajhenry** [comment]
I realized my build folder was deleted 🙄

**Comment by WsK** [comment]
I am seeing the same problem though. I do have the build directory after manually ran npm run build.
