### ISSUE TITLE
boilerplate of lit can not run

### ISSUE THREAD

**Issue by guocaoyi** [guocaoyi/create-chrome-ext#8]
Title:
boilerplate of lit can not run

Env:
node: v14.19.0
npm: 6.14.16
os: darwin (macOS Version:12.4)

Error:
popup page can't be rendered, (crx mode)
options page can't be rendered, (crx mode)

**Comment by ziofat** [comment]
the build folder is not generated when run `npm run dev`, and no `menifest.json` file when run `npm run build`
