### ISSUE TITLE
tailwindcss

### ISSUE THREAD

**Issue by qleml** [guocaoyi/create-chrome-ext#80]
I know this is not an issue but was someone able to add tailwindcss for react? if yes how?
Thanks!!

**Comment by brian7989** [comment]
Yes, I was able to.

1. Run `npm install -D tailwindcss postcss autoprefixer`
2. Run `npx tailwindcss init -p`
3. Set `tailwind.config.js` as 
```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

4. Add the following in `index.css` inside the component you are working with (ex: `index.css` inside /popup)
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
5. Start using TailwindCSS
```
<h1 className="text-3xl font-bold underline">
  Hello world!
</h1>
```

Linking official guide from TailwindCSS as reference [here](https://tailwindcss.com/docs/guides/vite)

**Comment by swapnawebdev** [comment]
How to work out in content script folder
