### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'sync')

### ISSUE THREAD

**Issue by ChrisGrigg** [guocaoyi/create-chrome-ext#81]
Forgive my ignorance if I'm barking up the wrong tree I'm brand new to chrome extension development. When I try `npm run dev` then visit `http://localhost:5173/sidepanel.html`

I get the error;

`react-dom_client.js?v=b833d8d0:16657 Uncaught TypeError: Cannot read properties of undefined (reading 'sync') at SidePanel.tsx:10:20`

In other words the `chrome.storage` property is undefined. Is there any way around this or does it need to be in a chrome extension environment i.e. load unpacked into the `chrome://extensions/`?

**Comment by dannyrb** [comment]
@ChrisGrigg did you get this sorted? I feel like I'm missing something obvious, or trying to see if I have to polyfill with alternative implementations to test locally
