### ISSUE TITLE
how can i update icon?

### ISSUE THREAD

**Issue by heart-er** [guocaoyi/create-chrome-ext#95]
i want to update icon in manifest.ts.
but it still old icon when i build.
![image](https://github.com/user-attachments/assets/43beb76b-64fa-4f34-b164-ea14a986f3d6)
![image](https://github.com/user-attachments/assets/3bb599bf-ac6e-4947-b369-0bd55217af9a)

**Comment by OfficialCRUGG** [comment]
@heart-er Did you solve this? If yes, can you please share your solution?
